route:
  receiver: 'telegram-notifications'

receivers:
- name: 'telegram-notifications'
  webhook_configs:
  - url: 'https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'bot'
        password: '<YOUR_BOT_TOKEN>'
    params:
      chat_id: ['<YOUR_CHAT_ID>']
      parse_mode: ['HTML']
      text: |
        ALERT: {{ .CommonAnnotations.summary }}{{ if .CommonLabels.severity }} (Severity: {{ .CommonLabels.severity }}){{ end }}
        Details:
        - Alert Name: {{ .CommonLabels.alertname }}
        - Instance: {{ .CommonLabels.instance }}
        - Description: {{ .CommonAnnotations.description }}
        - Status: {{ .Status }}
