
services:
  node-app:
    build:
      context: ./app
    ports:
      - "3001:3001"
    networks:
      - m

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    networks:
      - m
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    labels:
      - "prometheus-job=postgres"

  prometheus:
    image: prom/prometheus:v2.55.1 #v2.48.0-rc.2
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    networks:
      - m
    depends_on:
      - node-app
      # - postgres
      - node-exporter
      - postgres-exporter
      # - alertmanager
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - m
    volumes:
    - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    - ./monitoring/grafana/dashboards-data:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - m
    expose:
      - "9100"

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://myuser:password@postgres:5432/mydb?sslmode=disable"
    networks:
      - m
    expose:
      - "9187"
    depends_on:
      - postgres

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - m

networks:
  m:
    driver: bridge
