route:
  receiver: 'telegram-notifications'

receivers:
- name: 'telegram-notifications'
  webhook_configs:
  - url: 'https://api.telegram.org/bot7393622191:AAGJinuwWBKahgSzGdUL59kR_vzH1YuWbPs/sendMessage'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'bot'
        password: '7393622191:AAGJinuwWBKahgSzGdUL59kR_vzH1YuWbPs'
    params:
      chat_id: ['5516457807']
      parse_mode: ['HTML']
      text: |
        ALERT: {{ .CommonAnnotations.summary }}{{ if .CommonLabels.severity }} (Severity: {{ .CommonLabels.severity }}){{ end }}
        Details:
        - Alert Name: {{ .CommonLabels.alertname }}
        - Instance: {{ .CommonLabels.instance }}
        - Description: {{ .CommonAnnotations.description }}
        - Status: {{ .Status }}
