groups:
  - name: node-app-alerts
    rules:
      - alert: HighCpuUsage
        expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)) > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% (current value: {{ $value }})"

      - alert: HighMemoryUsage
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 0.2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Memory usage on {{ $labels.instance }}"
          description: "Memory available is less than 20% (current value: {{ $value }})"

      - alert: HighDiskUsage
        expr: node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} / node_filesystem_size_bytes < 0.2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Disk usage on {{ $labels.instance }}"
          description: "Disk space is less than 20% available (current value: {{ $value }})"

      - alert: HighNetworkUsage
        expr: sum(rate(node_network_receive_bytes_total[5m])) by (instance) > 1e8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Network Traffic on {{ $labels.instance }}"
          description: "Network traffic is high (current value: {{ $value }})"

  - name: postgres-alerts
    rules:
      - alert: PostgresHighConnectionCount
        expr: pg_stat_database_numbackends{datname!~"template[0-9]+"} > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High PostgreSQL connection count on {{ $labels.instance }}"
          description: "PostgreSQL is handling too many connections (current value: {{ $value }})"

      - alert: PostgresSlowQueries
        expr: rate(pg_stat_activity_backend_start[5m]) > 100
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Slow queries in PostgreSQL on {{ $labels.instance }}"
          description: "PostgreSQL is experiencing a high rate of slow queries (current value: {{ $value }})"

      - alert: PostgresHighTransactionRate
        expr: rate(pg_stat_database_xact_commit[5m]) > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High transaction rate in PostgreSQL on {{ $labels.instance }}"
          description: "PostgreSQL transaction rate is high (current value: {{ $value }})"
